#!/bin/bash

NAME="snowy"
DOMAIN="exposedcat"

SLUG="$NAME@$DOMAIN"
ARCHIVE="$SLUG.shell-extension.zip"

EXTENSIONS="/home/$USER/.local/share/gnome-shell/extensions"

build() {
  npx tsc
  cp -r metadata.json src/styles schemas dist
  glib-compile-schemas ./dist/schemas
}

install() {
  mkdir -p $EXTENSIONS
  rm -rf $EXTENSIONS/$SLUG
  mv dist $EXTENSIONS/$SLUG
}

case $1 in
clean)
  rm -rf dist node_modules $NAME.zip
  ;;
build)
  build
  ;;
pack)
  rm -fr $NAME.zip dist
  build
  pushd dist
  zip "../$ARCHIVE" -9r ./*.js ./*.css ./**/*.js ./**/*.css schemas/*.xml metadata.json
  popd
  ;;
install)
  install
  ;;
dev)
  build
  install
  dbus-run-session -- gnome-shell --nested --wayland
  ;;
*)
  echo "Unknown command '$1'"
  ;;
esac
