#!/bin/bash

NAME="snowy"
DOMAIN="exposedcat"

SLUG="$NAME@$DOMAIN"
ARCHIVE="$SLUG.shell-extension.zip"
EXTENSIONS="/home/$USER/.local/share/gnome-shell/extensions"

pack() {
	cd dist || exit
	zip -9r "../$ARCHIVE" .
	cd ..
}

build() {
  npx tsc
  cp -r metadata.json schemas dist

  glib-compile-schemas ./dist/schemas
  # ./scripts/compile-locales.sh "$SLUG"
}

inject() {
  mkdir -p "$EXTENSIONS"
  rm -rf "${EXTENSIONS:?}/$SLUG"
  unzip $ARCHIVE -d "$EXTENSIONS/$SLUG"
  glib-compile-schemas "$EXTENSIONS/$SLUG/schemas"
}

case $1 in
clean)
  rm -rf dist node_modules $ARCHIVE locale
  ;;
build)
  build
  ;;
cleanup)
	rm -f ./dist/schemas/gschemas.compiled
  ;;
pack)
	pack
  ;;
inject)
	inject
  ;;
translate)
  build
	./scripts/update-pot.sh
  ;;
uninstall)
  rm -rf "${EXTENSIONS:?}/$SLUG"
  ;;
dev)
	build
	pack
  inject
  dbus-run-session -- gnome-shell --nested --wayland
  ;;
*)
  echo "Unknown command '$1'"
  ;;
esac
